### ISSUE TITLE
Compatibility Issue with Zukan-icons-theme v0.4.5 and v0.4.6

### ISSUE THREAD

**Issue by aelmoghit** [53v3n3d4/Zukan-Icon-Theme#1]
Hi, I am encountering issues with the _Zukan-icons-theme_ package in versions **0.4.5** and **0.4.6**. The package no longer works as expected when used with the **Ayu theme**. Specifically, the icons fail to appear, and several console errors are displayed during the build process.

When I switched to the **Treble-theme**,  the theme works fine with Zuran. This suggests a potential compatibility problem with these versions of the package.  

**Environment Details:**  
- **Sublime Text Version:** 4192 (latest)  
- **Operating System:** Windows 11  
- **Sublime Text Theme:** Ayu theme  
- **Zukan-icons-theme Problematic Versions:**  v0.4.5, v0.4.6

**Comment by 53v3n3d4** [comment]
Hi, thanks for reporting this.

I installed `Ayu` and encountered an `IndexError: list index out of range`. Are you seeing the same error in the console?

**Comment by aelmoghit** [comment]
Yes, same message.

**Comment by 53v3n3d4** [comment]
I've fixed the issue. I'll leave this open for now to ensure everything is working correctly. Please let me know if you encounter any more problems.

I will be releasing a new version tomorrow.

**Comment by aelmoghit** [comment]
The problem still exists in the new version **0.4.7**.
Error: `IndexError: list index out of range`

I investigated the issue and found that the error occurs in this condition:
[search_themes.py](https://github.com/53v3n3d4/Zukan-Icon-Theme/blob/786df0c3a8414b48ab6bbffcb6bc15522197bd04/src/zukan_icon_theme/helpers/search_themes.py#L422)
```python
if not p.startswith(PKG_ZUKAN_ICON_THEME_FOLDER):
     theme_st_path = p
```
The issue arises because it compares paths with forward slashes (`/`) like `['Packages/ayu/ayu-mirage.sublime-theme', 'Packages/Zukan Icon Theme/icons/ayu-mirage.sublime-theme']` [L419](https://github.com/53v3n3d4/Zukan-Icon-Theme/blob/786df0c3a8414b48ab6bbffcb6bc15522197bd04/src/zukan_icon_theme/helpers/search_themes.py#L419) with a path using backslashes (\) like `PKG_ZUKAN_ICON_THEME_FOLDER = 'Packages\Zukan Icon Theme'`. . This causes the condition to always evaluate as `True`, leading to the wrong theme path being selected (`'Packages/Zukan Icon Theme/icons/ayu-mirage.sublime-theme'` instead of `'Packages/ayu/ayu-mirage.sublime-theme'`). As a result, an empty list `[]` is returned in [L426](https://github.com/53v3n3d4/Zukan-Icon-Theme/blob/786df0c3a8414b48ab6bbffcb6bc15522197bd04/src/zukan_icon_theme/helpers/search_themes.py#L426).

To fix this, I updated the code as follows:
```python
def get_sidebar_bgcolor(theme_name: str) -> str:
    """
    Get sidebar background color.

    Parameters:
    theme_name (str) -- theme name. E.g.: Default.sublime-theme

    Returns:
    (str) -- returns value 'dark' or 'light'
    """
    theme_sublime_path = sublime.find_resources(theme_name)

    for p in theme_sublime_path:
        if not p.startswith(PKG_ZUKAN_ICON_THEME_FOLDER.replace("\\","/")):
            theme_st_path = p
   
    if theme_st_path:
        bgcolor = find_sidebar_background(theme_st_path)
    
    return bgcolor[0] 
```

**Comment by 53v3n3d4** [comment]
Yes, I was testing on both Windows and Linux VM. I was thinking in removing `os.path.join` for the partials paths.

I see your suggestion to use `PKG_ZUKAN_ICON_THEME_FOLDER.replace("\\", "/")`—that’s a good approach. Do you want to fix it?

**Comment by aelmoghit** [comment]
Hi, **53v3n3d4**
I encountered another issue related to our previous discussion: an `IndexError: list index out of range`. This error occurs because there are three paths associated with the applied theme:
`['Packages/ayu/ayu-mirage.sublime-theme', 
 'Packages/Zukan Icon Theme/icons/ayu-mirage.sublime-theme', 
 'Packages/User/ayu-mirage.sublime-theme']`.

The third path corresponds to my custom modifications of the theme, but it does not include the `layer0.tint` attribute.

To fix this, I updated the code as follows:
```python
def get_sidebar_bgcolor(theme_name: str) -> str:
    """
    Get sidebar background color.

    Parameters:
    theme_name (str) -- theme name. E.g.: Default.sublime-theme

    Returns:
    (str) -- returns value 'dark' or 'light'
    """
    theme_sublime_path = sublime.find_resources(theme_name)
    
    for p in theme_sublime_path:
        if (not p.startswith('Packages/Zukan Icon Theme')
            and find_sidebar_background(p)
            ):
            theme_st_path = p

    if theme_st_path:
        bgcolor = find_sidebar_background(theme_st_path)

    return bgcolor[0]
```

I changed the condition inside the loop by adding another condition to check the returned bgcolor list.

**Comment by 53v3n3d4** [comment]
Hi @ABDELMOGHIT-HOUMADI,

You're right, I hadn’t thought about theme customization - good cacht. Instead of running `find_sidebar_background`, have you tried checking for the 'Packages/User' partial path first? It might help avoid searching in theme files.
